<?php

$gameProductList =[
    [
        "id" => 0,
        "name" => "Final Fantasy VII",
        "description" => "Un jeu de grand pères. C'est ultra moche et les combats popent au pif. WTF !?",
        "platform" => "PS1",
        "genres" => ['J-RPG', 'Cyberpunk'],
        "releasedAt" => new DateTime('31 Jan 1997'),
        "image" => "finalfantasyvii.jpg",
        "price" => 239.99,
    ],
    [
        "id" => 1,
        "name" => "Deus Ex",
        "description" => "Qui a mis du RPG dans mon FPS !? En plus je capte rien au scénario.",
        "platform" => "PC",
        "genres" => ['ImmersiveSim', 'FPS', 'Cyberpunk'],
        "releasedAt" => new DateTime('22 Jun 2000'),
        "image" => "deusex.jpeg",
        "price" => 129.99,
    ],
    [
        "id" => 2,
        "name" => "Resident Evil",
        "description" => "Les monstres vous tuent en deux morsures, on a jamais de balles et on tourne en rond. Resident Evil 6 était bien meilleur !",
        "platform" => "Gamecube",
        "genres" => ['Survival Horror'],
        "releasedAt" => new DateTime('22 Mar 2002'),
        "image" => "residentevil.png",
        "price" => 19.99,
    ],
    [
        "id" => 3,
        "name" => "Fifa 2022",
        "description" => "Tout simplement incroyable ! Le titre transcende son prédécesseur avec une refonte totale du gameplay. En plus les microtransactions sont pas si chers, en vrai.",
        "platform" => "Serie X",
        "genres" => ['Sport'],
        "releasedAt" => new DateTime('26 Sep 2021'),
        "image" => "fifa.jpeg",
        "price" => 79.99,
    ],
    [
        "id" => 4,
        "name" => "Elden Ring",
        "description" => "Super dur en vrai. On pourrait dire que c'est un peu le Dark Souls des Dark Souls ?",
        "platform" => "PS5",
        "genres" => ['A-RPG', 'Dark Fantasy'],
        "releasedAt" => new DateTime('24 Feb 2022'),
        "image" => "eldenring.jpg",
        "price" => 79.99,
    ],
    [
        "id" => 5,
        "name" => "The Legend of Zelda -Ocarina of Time-",
        "description" => "C'est nul mais c'est culte, donc ça se revend bien cher sa race !",
        "platform" => "Nintendo64",
        "genres" => ['A-RPG', 'Dark Fantasy'],
        "releasedAt" => new DateTime('21 Nov 1998'),
        "image" => "ocarina.jpg",
        "price" => 3999.99,
    ],
    [
        "id" => 6,
        "name" => "Super Mario 64",
        "description" => "Je suis tombé dans l'eau devant le chateau au début et j'arrive pas à remonter ça me saoule ce jeu !",
        "platform" => "Nintendo64",
        "genres" => ['Plateformer'],
        "releasedAt" => new DateTime('23 Jun 1996'),
        "image" => "mario.jpg",
        "price" => 3999.99,
    ],
    [
        "id" => 7,
        "name" => "Doom Eternal",
        "description" => "Ca va trop vite je pige rien. Pourquoi on a 10 flingues en même temps et pas juste deux comme dans Call of ?",
        "platform" => "PC",
        "genres" => ['FPS'],
        "releasedAt" => new DateTime('20 Mar 2020'),
        "image" => "doom.jpg",
        "price" => 49.99,
    ],
    [
        "id" => 8,
        "name" => "Ace Attorney - Phoenix Wright",
        "description" => "Délire c'est un bouquin le jeu en fait, ils ont abusé les mecs !",
        "platform" => "Switch",
        "genres" => ['VisualNovel', 'Detective'],
        "releasedAt" => new DateTime('7 Feb 2012'),
        "image" => "aceattorney.jpg",
        "price" => 39.99,
    ],
    [
        "id" => 9,
        "name" => "Cruelty Squad",
        "description" => "Je crois que j'ai fait un badtrip, gros !",
        "platform" => "PC",
        "genres" => ['FPS', 'ImmersiveSim'],
        "releasedAt" => new DateTime('4 Jan 2021'),
        "image" => "cruelty-squad.jpg",
        "price" => 29.99,
    ],
    [
        "id" => 10,
        "name" => "Forza Horizon 5",
        "description" => "¡Ay, caramba! Forza Horizon 5 fait mûrir sous le soleil mexicain une recette concoctée par Playground Games ayant déjà régalé des millions de pilotes. Tel un antojito, Forza Horizon 5 se déguste dans la bonne humeur avec n'importe qui, n’importe quand. Roulant sur tout ce qui a déjà été fait techniquement et profitant du tremplin Xbox Series X pour tamponner les cieux, le soft de Microsoft gravit le volcan du fun et déverse une coulée d’épreuves exaltantes à vivre seul ou à plusieurs. C’est le festival de la décennie.",
        "platform" => "PC",
        "genres" => ['Racing', 'Sport'],
        "releasedAt" => new DateTime('4 Nov 2021'),
        "image" => "forza.jpg",
        "price" => 29.99,
    ],
    [
        "id" => 11,
        "name" => "Dead or Alive : Xtrem Beach Volleyball 2",
        "description" => "Le meilleur de la série, sans aucun doute ! Le gameplay est ultra profond.",
        "platform" => "Xbox",
        "genres" => ['Sport'],
        "releasedAt" => new DateTime('2 Jan 2003'),
        "image" => "deadoralive.jpg",
        "price" => 19.99,
    ],
    [
        "id" => 12,
        "name" => "Persona 5 - Strikers",
        "description" => "J'y ai pas joué.",
        "platform" => "Switch",
        "genres" => ['A-RPG', 'Visual Novel'],
        "releasedAt" => new DateTime('20 Feb 2020'),
        "image" => "personastrikers.jpg",
        "price" => 59.99,
    ],
 
];
